namespace DcsMissionReader.Models
{
    /// <summary>
    /// Command line options for the application. This class is used to store the options that are passed to the application when it is run from the command line. The options include whether to create HTML and JSON output, whether to perform a full export, and a list of mission files to process.
    /// </summary>
    public class AppOptions
    {
        /// <summary>
        /// If true, the application will generate HTML output based on the processed mission files. This option indicates that the user wants to create an HTML representation of the mission data, which can be useful for visualizing the mission information in a web browser or sharing it with others in a more user-friendly format. When this option is enabled, the application will likely include a step in the processing pipeline to convert the extracted mission data into HTML format and save it to a file or output it in some way.
        /// </summary>
        public bool CreateHtml { get;  set; } = false;

        /// <summary>
        /// If true, the application will generate JSON output based on the processed mission files. This option indicates that the user wants to create a JSON representation of the mission data, which can be useful for further processing, analysis, or integration with other tools. When this option is enabled, the application will likely include a step in the processing pipeline to convert the extracted mission data into JSON format and save it to a file or output it in some way.
        /// </summary>
        public bool CreateJson { get;  set; } = false;

        /// <summary>
        /// If true, the application will perform a full export of all available data from the mission files. This option indicates that the user wants to extract and export all possible information from the DCS mission files, rather than just a subset of data. When this option is enabled, the application will likely include more detailed information in the output, which may be useful for users who want a comprehensive view of the mission data.
        /// </summary>
        public bool FullExport { get;  set; } = false;

        /// <summary>
        /// List of mission files to process. This property holds the list of mission files that the application will read and process based on the command line arguments. The application will look for files with a .miz extension in the command line arguments and add them to this list for processing.
        /// </summary>
        public List<string> MissionFiles { get;  set; } = [];

        /// <summary>
        /// Units system to use for output values. This property allows the user to specify which unit system they want to use for the output generated by the application. The default value is UnitsSystem.Real, which means that if the user does not specify a unit system, the application will use the Real (SAE/Imperial) system for output values. Users can change this to UnitsSystem.Metric if they prefer to have the output in metric units instead.
        /// </summary>
        public UnitsSystem Units { get;  set; } = UnitsSystem.Real;

        /// <summary>
        /// If true, the application will generate KML output based on the processed mission files. This option indicates that the user wants to create a KML representation of the mission data, which can be useful for visualizing the mission information in mapping applications like Google Earth. When this option is enabled, the application will likely include a step in the processing pipeline to convert the extracted mission data into KML format and save it to a file or output it in some way.
        /// </summary>
        public bool CreateKml { get;  set; } = false;

        /// <summary>
        /// If true, the application will display the version information and exit. This option allows users to quickly check which version of DcsMissionReader they are running without having to navigate through menus or check file properties. When this option is enabled, the application will retrieve the version information from the assembly metadata and display it in the console before exiting. 
        /// </summary>
        public bool ShowVersion { get;  set; } = false;

        /// <summary>
        /// If true, the application will display the help information and exit. This option allows users to quickly access the usage instructions and available command line options for DcsMissionReader. When this option is enabled, the application will print a help message to the console that includes a description of the application, a list of available command line options, and an example of how to use the application. After displaying the help information, the application will exit without processing any mission files.    
        /// </summary>
        public bool ShowHelp { get;  set; } = false;    

        /// <summary>
        /// If true, the application will check for registration of the DCS mission file format in the Windows registry. This option allows users to verify that the necessary registry entries for handling DCS mission files are present on their system. When this option is enabled, the application will likely include a step in the processing pipeline to check the Windows registry for the appropriate keys and values that indicate support for DCS mission files. If the required registry entries are missing or incorrect, the application may display a warning message or provide instructions on how to register the file format properly. 
        /// </summary>
        public bool CheckRegistration { get;  set; } = false;

        /// <summary>
        /// If true, the application will install the necessary registry entries for handling DCS mission files. This option allows users to register the DCS mission file format on their system. When this option is enabled, the application will likely include a step in the processing pipeline to create the appropriate keys and values in the Windows registry.
        /// </summary>
        public bool InstallRegistration { get;  set; } = false; 

        /// <summary>
        /// If true, the application will uninstall the registry entries for handling DCS mission files. This option allows users to unregister the DCS mission file format on their system. When this option is enabled, the application will likely include a step in the processing pipeline to remove the appropriate keys and values from the Windows registry.
        /// </summary>
        public bool UninstallRegistration { get;  set; } = false;

        /// <summary>
        /// Create a brief post-briefing report in KML format. This option indicates that the user wants to generate a simplified report of the mission's post-briefing information, which may include key events, outcomes, and other relevant data from the mission. When this option is enabled, the application will likely include a step in the processing pipeline to extract the necessary information from the mission files and convert it into KML format for output. The generated KML file can then be used for visualization or analysis of the mission's post-briefing data.
        /// </summary>
        public bool PostBrief { get; set; }

        /// <summary>
        /// Location of the .miz file to read for generating the post-briefing report. This property specifies the path to the DCS mission file that contains the data needed to create the post-briefing report. The application will read this .miz file, extract the relevant information, and use it to generate the KML output for the post-briefing report. If this property is not set or if the specified file does not exist, the application may display an error message or prompt the user to provide a valid .miz file path for generating the post-briefing report.
        /// </summary>
        public string? PostBriefAcmiZipFilePath { get; set; }

        /// <summary>
        /// Location to save the generated KML file for the post-briefing report. This property specifies the path where the application will save the KML output generated from the post-briefing report. If this property is not set, the application may use a default location or prompt the user to specify a valid output path for the KML file. The generated KML file can then be used for visualization or analysis of the mission's post-briefing data in mapping applications like Google Earth.
        /// </summary>
        public string? PostBriefKmlOutputPath { get; set; }

        /// <summary>
        /// If no mission files are provided or certain switches are not specified, the application will consider the command line arguments to be invalid and will likely display an error message or prompt the user to provide valid input. This property checks if there are no mission files specified and none of the other options that would cause the application to exit early (like showing help or version information) are enabled. If this condition is true, it indicates that the user has not provided any valid input for the application to process, which can be considered an error state.
        /// </summary>
        public bool HasErrors => !PostBrief && string.IsNullOrEmpty(PostBriefAcmiZipFilePath) && MissionFiles.Count == 0 && !ShowHelp && !ShowVersion && !CheckRegistration && !InstallRegistration && !UninstallRegistration;

        /// <summary>
        /// Max number of track points per unit to include in the post-briefing KML report. This property allows the user to specify a limit on the number of track points that will be included in the generated KML file for the post-briefing report. Track points represent the movement and actions of units in the DCS mission, and including too many track points can lead to performance issues or excessively large KML files. By setting a maximum number of track points, the application can ensure that the generated KML file remains manageable and performs well when visualized in mapping applications. The default value is set to 75, but users can adjust this as needed based on their preferences and requirements for the post-briefing report.
        /// </summary>
        public int PostBriefMaxTrackPoints { get; internal set; } = 75;
    }
}
