namespace DcsMissionReader.Models
{
    /// <summary>
    /// Command line options for the application. This class is used to store the options that are passed to the application when it is run from the command line. The options include whether to create HTML and JSON output, whether to perform a full export, and a list of mission files to process.
    /// </summary>
    public class AppOptions
    {
        /// <summary>
        /// If true, the application will generate HTML output based on the processed mission files. This option indicates that the user wants to create an HTML representation of the mission data, which can be useful for visualizing the mission information in a web browser or sharing it with others in a more user-friendly format. When this option is enabled, the application will likely include a step in the processing pipeline to convert the extracted mission data into HTML format and save it to a file or output it in some way.
        /// </summary>
        public bool CreateHtml { get; set; }

        /// <summary>
        /// If true, the application will generate JSON output based on the processed mission files. This option indicates that the user wants to create a JSON representation of the mission data, which can be useful for further processing, analysis, or integration with other tools. When this option is enabled, the application will likely include a step in the processing pipeline to convert the extracted mission data into JSON format and save it to a file or output it in some way.
        /// </summary>
        public bool CreateJson { get; set; }

        /// <summary>
        /// If true, the application will perform a full export of all available data from the mission files. This option indicates that the user wants to extract and export all possible information from the DCS mission files, rather than just a subset of data. When this option is enabled, the application will likely include more detailed information in the output, which may be useful for users who want a comprehensive view of the mission data.
        /// </summary>
        public bool FullExport { get; set; }

        /// <summary>
        /// List of mission files to process. This property holds the list of mission files that the application will read and process based on the command line arguments. The application will look for files with a .miz extension in the command line arguments and add them to this list for processing.
        /// </summary>
        public List<string> MissionFiles { get; set; } = [];

        /// <summary>
        /// Units system to use for output values. This property allows the user to specify which unit system they want to use for the output generated by the application. The default value is UnitsSystem.Real, which means that if the user does not specify a unit system, the application will use the Real (SAE/Imperial) system for output values. Users can change this to UnitsSystem.Metric if they prefer to have the output in metric units instead.
        /// </summary>
        public UnitsSystem Units { get; set; } = UnitsSystem.Real;

        /// <summary>
        /// If true, the application will generate KML output based on the processed mission files. This option indicates that the user wants to create a KML representation of the mission data, which can be useful for visualizing the mission information in mapping applications like Google Earth. When this option is enabled, the application will likely include a step in the processing pipeline to convert the extracted mission data into KML format and save it to a file or output it in some way.
        /// </summary>
        public bool CreateKml { get; set; } = false;
    }
}
