namespace DcsMissionReader.Models
{
    /// <summary>
    /// Units system to use for output values. This enum defines the possible unit systems that can be used when generating output from the DCS mission files. The Metric system uses kilometers, meters per second, hectopascals, and degrees Celsius, while the Real (SAE/Imperial) system uses miles, knots, inches of mercury, and degrees Fahrenheit. This allows users to choose their preferred unit system for the output data generated by the application.
    /// </summary>
    public enum UnitsSystem
    {
        /// <summary>
        /// Metric system, which uses kilometers for distance, meters per second for speed, hectopascals for pressure, and degrees Celsius for temperature. This is the standard unit system used in most of the world and is based on the International System of Units (SI).
        /// </summary>
        Metric,   

        /// <summary>
        /// Real system (SAE/Imperial), which uses miles for distance, knots for speed, inches of mercury for pressure, and degrees Fahrenheit for temperature. This system is commonly used in the United States and other countries that follow the Imperial system.
        /// </summary>  
        Real      
    }
}
